### ISSUE TITLE
Why use Quicklisp in CI?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nfiles#9]
@aartaka https://github.com/atlas-engineer/nfiles/actions/runs/3409258951/jobs/5670800095 fails because `(asdf:system-relative-pathname :nfiles "test-data")` does not work.  Indeed, the CI uses Quicklisp and not ASDF.

Was it a deliberate choice?
Why not work like Nyxt which has been working reliable without Quicklisp so far?

**Comment by aartaka** [comment]
Because ASDF comes together with submodules, and we don't use submodules in most libraries we use. See https://github.com/atlas-engineer/ntemplate/issues/5

**Comment by aartaka** [comment]
But wait, does Quicklisp not use ASDF underneath?

**Comment by Ambrevar** [comment]
Yup, but as you can see, not properly enough :(

Why not use submodules for libraries?

- It would make them reproducible.
- It pins the commits, which is good practice.  (Kind of the same, but good to emphasize.)
- Removes dependency on Quicklisp.
- Does not require HTTP (unencrypted) like Quicklisp.

**Comment by Ambrevar** [comment]
See #11.
